name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Publish step
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
        run: bash ./.github/scripts/exec-publish.sh

  deploy:
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - uses: actions/checkout@v4
      - name: Deploy step
        env:
          PATH_TO_COMPOSE_FILE: ${{ secrets.PATH_TO_COMPOSE_FILE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: bash ./.github/scripts/exec-deploy.sh
